apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: loadbalancerdefaults
spec:
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
  interfaces:
  - ^enp+|^eth+
  externalIPs: true
  loadBalancerIPs: true
