apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ingress-pool"
spec:
  cidrs:
  - cidr: "172.31.0.96/28"
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
