apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-ingress
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: private-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.8.2
    chart: ingress-nginx
    helm:
      valueFiles: []
      values: |
        controller:
          name: private-controller
          ingressClass: private-nginx
          ingressClassByName: "true"
          reportIngressStatus:
            enableLeaderElection: "true"
          ingressClassResource:
            name: private-nginx
            enabled: "true"
            controllerValue: k8s.io/private-controller
          service:
            type: LoadBalancer
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
