apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-ingress
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: private-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.nginx.com/stable'
    targetRevision: 1.x
    chart: nginx-ingress
    helm:
      valueFiles: []
      parameters:
        - name: controller.ingressClass.name
          value: private-nginx
        - name: controller.name
          value: private-controller
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
