apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-ingress
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: public-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.8.x
    chart: ingress-nginx
    helm:
      valueFiles: []
      parameters:
        - name: controller.name
          value: public-controller
        - name: controller.ingressClassResource.name
          value: public-nginx
        # - name: controller.ingressClassByName
        #   value: "true"
        - name: controller.ingressClassResource.controllerValue
          value: nginx.org/public-controller
        - name: controller.service.type
          value: LoadBalancer
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
