# tasks file
---
- name: facts | set
  ansible.builtin.set_fact:
    kernel_version: "{{ ansible_kernel | regex_search('^([0-9]+\\.[0-9]+\\.[0-9]+)') }}"
  tags:
    - configuration
    - ufw
    - ufw-facts

# see https://askubuntu.com/a/1064533/261010, https://www.spinics.net/lists/netfilter-devel/msg55682.html
- name: fix dropped ssh sessions
  ansible.builtin.import_tasks: fix-dropped-ssh-sessions.yml
  when:
    - kernel_version is version('4.14', '>=')
    - kernel_version is version('5', '<')
  tags:
    - configuration
    - ufw
    - ufw-fix-dropped-ssh-sessions

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - ufw
    - ufw-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - ufw
    - ufw-configure

- name: start and enable service
  community.general.ufw:
    state: enabled
  tags:
    - configuration
    - ufw
    - ufw-start-enable-service
