- name: Add Kube-Prometheus Helm Repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy Kube Prometheus
  kubernetes.core.helm:
    kubeconfig: {{ ANSIBLE_USER_HOME }}.kube/config #change to actual relative path to deploy
    name: kube-prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    values_files: /templates/kube-prometheus.values.yaml
