apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ingress-pool"
spec:
  cidrs:
  - cidr: "192.168.1.100/28"
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress