apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-server
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: mediaserver
    server: 'https://kubernetes.default.svc'
  source:
    path: "Kubernetes Media Server"
    repoURL: >-
      https://github.com/Tanchwa/DevOps-Projects
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
