apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: mediaserver
spec:
  destination:
    name: ''
    namespace: mediaserver
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bjw-s.github.io/helm-charts'
    targetRevision: 1.5.1
    chart: app-template
    helm:
      values: |
        test 
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
