apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-certificates
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: 'Manifests/Certificates'
    repoURL: >-
      https://github.com/Tanchwa/Homelab-Iac
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

