---
# tasks file for kubectl
- name: Install kubectl
  apt:
    name: kubectl={{ kubectl_version }}
    state: present
    update_cache: yes
    allow_change_held_packages: true
    allow_downgrade: true
  tags: install

- name: Hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold