apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-home
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: smarthome
    server: 'https://kubernetes.default.svc'
  source:
    path: "Manifests/Smart Home"
    repoURL: >-
      https://github.com/Tanchwa/Homelab-IaC
    targetRevision: asutliff/k8s-device
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
