# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

input_boolean:
  stop_tts:
    name: Stop TTS
    initial: off
    icon: mdi:stop-circle-outline

light: !include_dir_merge_named Devices/light/
mediaplayer: !include_dir_merge_named Devices/mediaplayer/
automation: !include_dir_merge_list Automations/
script: !include scripts.yaml
scene: !include scenes.yaml
groups: !include_dir_merge_named Rooms/
sensor: !incude_dir_m

## NEW STUFF 
packages:
  lights: !incude Packages/Lights/main.yaml
