# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

input_boolean:
  stop_tts:
    name: Stop TTS
    initial: off
    icon: mdi:stop-circle-outline

homeassistant:
  packages:
    lights: !include Packages/Lights/main.yaml
    mediaplayers: !include Packages/Media_Players/main.yaml

automation mine: !include_dir_merge_list Automations/
automation core: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

