# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ ufw_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - ufw-install-dependencies
