apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoist-webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tanchwa/Homelab-IaC'
    path: Manifests/Todoist-Reclaim-Webhook
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: todoist-webhook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
