apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-defaults
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: "Manifests/Networking"
    repoURL: >-
      https://github.com/Tanchwa/Homelab-IaC
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
