collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.docker
    type: git
  - name: https://github.com/gekmihesg/ansible-openwrt
    type: git
