apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 51.x
    chart: kube-prometheus-stack
    helm:
      valueFiles: []
      values: |
        prometheus:
        prometheusSpec:
            scrapeConfigSelector:
              matchLabels:
                prometheus: system-monitoring-prometheus
        grafana:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "cloudflare-issuer"
              kubernetes.io/ingress.class: "public-nginx"
            hosts: 
              - "grafana.andrewsutliff.com"
            tls:
              - hosts:
                  - "grafana.andrewsutliff.com"
                secretName: grafana-http-tls
            paths: 
              - "/"
        alertmanager:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "cloudflare-issuer"
              kubernetes.io/ingress.class: "private-nginx"
            hosts: 
              - "alertmanager.andrewsutliff.com"
            paths: 
              - "/"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
