apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 51.x
    chart: kube-prometheus-stack
    helm:
      valueFiles: []
      parameters:
        - name: ingress.ingressClassName
          value: "private-nginx"
        - name: ingress.enabled
          value: "true"
        - name: ingress.annotations
          value: |
            cert-manager.io/cluster-issuer: "cloudflare-issuer"
        - name: ingress.hosts
          value: "grafana.andrewsutliff.com"
        - name: ingress.paths
          value: "/"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
