apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cnpg-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://cloudnative-pg.github.io/charts'
    targetRevision: v0.27.0
    chart: cloudnative-pg
    helm:
      valueFiles: []
      values: |
        monitoring:
          podMonitorEnabled: true
          grafanaDashboard:
            enabled: true
            namespace: monitoring
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
