apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: nextcloud
    server: 'https://kubernetes.default.svc'
  source:
    path: 'charts/nextcloud'
    repoURL: 'https://nextcloud.github.io/helm/'
    targetRevision: nextcloud-4.6.2
    chart: nextcloud
    helm:
      valueFiles: []
      values:
        nextcloud:
          extraVolumes:
          extraVolumeMounts:
        ingress:
          enabled: "true"
          className: "private-nginx"
          annotations:
            - cert-manager.io/cluster-issuer: "cloudflare-issuer" 
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
