apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: productivity
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://kolaente.dev/vikunja/helm-chart.git'
    targetRevision: HEAD
    helm:
      valueFiles: []
      values: |
        api:
          persistence:
            data:
              enabled: true
              accessMode: ReadWriteOnce
              size: 10Gi
              mountPath: /app/vikunja/files
              storageClass: longhorn
          configMaps:
            config:
              enabled: true
              data:
                config.yml: |
                  service:
                    frontendUrl: vikunja-frontend.productivity.svc.cluster.local
          env:
            VIKUNJA_DATABASE_HOST: vikunja-postgresql.productivity.svc.cluster.local
        frontend:
          env:
            VIKUNJA_API_URL: vikunja-api.productivity.svc.cluster.local/api
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

