apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-tests
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ai-tests
    server: 'https://kubernetes.default.svc'
  source:
    path: "Manifests/AI"
    repoURL: >-
      https://github.com/Tanchwa/Homelab-IaC
    targetRevision: refs/heads/asutliff/milvus-cluster-edits
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
