---
- name: Create NAT Iptables Rule
  iptables:
    table: '{{ table }}'
    chain: '{{ chain }}'
    out_interface: '{{ masquerade_out_interface }}'
    source: '{{ masquerade_source }}'
    destination: '{{ masquerade_destination }}'
    jump: '{{ jump }}'
    protocol: '{{ masquerade_protocol }}'
    comment: Ansible Iptables '{{ chain }}' Rule
    notify: Enable IPv4 forwarding
    notify: Save Current '{{ table }}' State to System File

# iptables notes
# may need to consider enabling iptables-persistent, ansible only configures the tables in memory
# rules.v4
# IPtables chains: Input, Output, Forward
# BASIC routing set up only considers input, and destination
# this does not change the Ip, or force it to go to a different destination than originally designated
# MODIFYING
# sudo iptables -t (table) nat -A (when to use this rule) POSTROUTING -j (jump) MASQUERADE
# sudo iptables -t nat -s (source) 192.168.0.0/16 
#
