apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: andrew.sutliff.1@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: andrew.sutliff.1@gmail.com
          apiTokenSecretRef:
            name: cloudflare-token
            key: api-token
      selector:
        dnsZones:
        - 'andrewsutliff.com'
