- hosts: ansible_controller
  become: yes
  become_user: asutliff
  tasks:
  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
    community.crypto.openssl_privatekey:
      path: ~/ansible.key
  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: ~/ansible.csr
      privatekey_path: ~/ansible.key
      common_name: asutliff
      organization_name: system:authenticated
  tags: keygen


- hosts: controlplane_nodes #figure out how to limit this to only a single host
  become_user: asutliff
  tasks:
  - name: Copy CSR to Controleplane
    copy:
      src: ~/ansible.csr
      dest: ~/
  - name: Convert CSR into Usable format
    shell: |
      cat ansible.csr | base64 | tr -d '\n'
    register: ansible_csr
  - name: Create CSR Kubernetes Object
    shell: |
      cat <<EOF | kubectl create -f -
      apiVersion: certificates.k8s.io/v1
      kind: CertificateSigningRequest
      metadata:
        name: asutliff
      spec:
        signerName: kubernetes.io/kube-apiserver-client
        usages:
        - digital signature
        - key encipherment
        - client auth
        request:
          "{{ ansible_csr.stdout }}"
      EOF
  - name: Sign CSR
    command: kubectl certificate approve asutliff
  - name: Output Signed CSR Certificate
    shell: |
      kubectl get csr asutliff -o yaml | grep -e '^  certificate:' | sed 's/certificate://' | tr -d [:space:] | base64 --decode
    register: signed_cert
  - name: Copy Signed CSR Certificate to master
    copy:
      content: "{{ signed_cert.stdout }}"
      dest: ~/ansible.crt
  - name: Copy Signed CSR Certificate to Controller
    fetch:
      src: ansible.crt
      dest: /tmp
  - name: Copy CA cert to Controller
    fetch:
      src: /etc/kubernetes/pki/ca.crt
      dest: /tmp
  tags: csr

- hosts: ansible_controller
  become: yes
  become_user: asutliff
  vars:
    kube_user: "asutliff"
    kube_config_path: "/home/{{ kube_user }}/.kube/config"
    certificate_path: "/tmp/k8s-controlplane/ansible.crt"
    ca_certificates_path: "/tmp/k8s-controlplane/etc/kubernetes/pki/ca.crt"
    key_path: "/home/{{ kube_user }}/ansible.key"
    cluster_name: "kubernetes"
    cluster_address: "https://k8s-controlplane:6443"
    new_user_config: true
    default_config: false
  roles:
    - kubeconfig

# - hosts: ansible_controller
#   tasks:
#   - name: Cleanup temp files
#     file:
#       path: /tmp/k8s-controlplane/
#       state: absent