---
- hosts: ansible_controller
  gather_facts: true
  vars:
    kube_ports: 
      - 6443 
      - 2379
      - 2380
      - 10250
      - 10259his
      - 10257
      #networking?
      - 8472 #udp
      - 4240 #tcp
      - 8472 #udp, egress
      - 4240 #tcp, egress
      - 53 #allow out to upstream router
    kube_hosts: "{{ ansible_all_ipv4_addresses | difference([hostvars[inventory_hostname].ansible_default_ipv4.address]) }}"
  tasks:
    - name: Create ufw_rules map
      set_fact: 
        ufw_rules: "{{ ufw_rules | default([]) + [{'rule': 'allow', 'direction': 'in', 'to_port': item.0, 'from_ip': item.1}] }}"
      loop: "{{ kube_ports | product(kube_hosts) | list }}"
      loop_control:
        loop_var: item

    - name: Debug
      debug:
        var: kube_hosts
  tags:
    - set-ufw-rules

- hosts: controlplane_nodes, worker_nodes
  become: yes
  become_user: root
  vars:
    containerd_config_default_write: true
    containerd_config_cgroup_driver_systemd: true
    kubeadm_version: 1.25.0-00
    kubectl_version: 1.25.0-00
    kubelet_version: 1.25.0-00
    # ufw_rules: item
    # with_items: 
    #  ufw_rules: "{{ ufw_rules }}"
  roles:
    - kernel_config
    - repositories
    # - ansible-ufw
    - kubeadm
    - kubelet
    - kubectl
    - containerd
  tags: pre-k8s-init

- hosts: controlplane_nodes
  become: yes
  become_user: root
  vars:
    pod_network_cidr: 10.0.0.0/8 # flannel: 10.244.0.0/16 # pod CIDR range for cluster init, change this to match your CNI pluggin CIDR configuration
    host_ip: "{{ ansible_default_ipv4.address }}"
    host_name: "{{ inventory_hostname }}"
    kube_user: "asutliff"
    kube_config_path: "/home/{{ kube_user }}/.kube/config"
    default_config: true
    new_user_config: false
  roles:
    - cluster_init
    - kubeconfig
  tags: cluster-init

- hosts: worker_nodes
  become: yes
  become_user: root
  roles:
    - add_node
  tags: add-node

- hosts: controlplane_nodes
  become: yes
  become_user: asutliff
  vars:
    cilium: true #set the name of the CNI plugin you want to use to true, currently supports only flannel or cilium
    kube_user: "asutliff"
  roles:
    - cni
  tags: k8s-network

- hosts: ansible_controller
  become: true
  roles:
    - argo_cd