# Follows the desired entity arround with currently playing media

binary_sensor:
  - platform: template
    sensors:
      follow_mode:
        friendly_name: "Follow Mode"
        value_template: "{{ is_state('input_boolean.follow_mode', 'on') }}"

automation: 
  - alias: "Change Media Location"
    trigger:
      - platform: ESPRESENSE?
        entity_id: ESPRESENSE.
    
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.follow_mode
          state: "on"
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.mqqt_room
              state: "living_room"
            - condition: state
              entity_id: sensor.mqqt_room
              state: "bedroom"
            - condition: state
              entity_id: sensor.mqqt_room
              state: "kitchen"
    action:
      service: media_player.media_play
      target:
        entity_id: >-
          {% if is_state("sensor.mqqt_room", "living_room") %}
            media_player.living_room_speaker
          {% elif is_state("sensor.mqqt_room", "bedroom") %}
            media_player.bedroom_speaker
          {% elif is_state("sensor.mqqt_room", "kitchen") %}
            media_player.kitchen_speaker
          {% endif %}
      data:
        media_content_type: music
        media_
