---
# defaults file for containerd
# Package options.
containerd_package: containerd.io
containerd_package_state: present

# Service options.
containerd_service_state: started
containerd_service_enabled: true

# Write a default containerd config.toml file.
containerd_config_default_write: true

# Set systemd as cgroup driver in config.toml
# Only use with containerd_config_default_write: true
containerd_config_cgroup_driver_systemd: true