apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: apollo
    server: 'https://kubernetes.default.svc'
  source:
    path: 'helm/chart/router'
    repoURL: 'https://github.com/apollographql/router'
    targetRevision: HEAD
    helm:
      valueFiles: []
      values: |
        managedFederation:
          existingSecret: apollo-api-key
          existingSecretKeyRefKey: apollo-api-key
          graphRef: apollo-supergraph-k8s-5c5ffa@current
        extraContainers:
          - name: coprocessor
            image: ghcr.io/tanchwa/apollo-k8s-reference-arch/coprocessor
            ports:
              - containerPort: 8081
        ingress:
          enabled: true
          className: private-nginx
          annotations:
              cert-manager.io/cluster-issuer: "cloudflare-issuer"
          hosts: 
            - host: "apollo.andrewsutliff.com"
              paths: 
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "apollo.andrewsutliff.com"
              secretName: apollo-router-http-tls
        #extraVolumeMounts:
        # - name: rhai-volume
        #    mountPath: /dist/rhai
        #    readOnly: true
        #extraVolumes:
        #  - name: rhai-volume
        #    configMap:
        #      name: rhai-config
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

