# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
# this config can be found at https://github.com/zilliztech/milvus-operator/blob/main/config/samples/milvus_cluster_default.yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: {}
  components: {}
  config: {}
