apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: immich
    server: 'https://kubernetes.default.svc'
  source:
    path: 'charts/immich'
    repoURL: 'https://immich-app.github.io/immich-charts'
    targetRevision: v0.7.1
    chart: immich
    helm:
      valueFiles: []
      values: |
        image:
          tag: v1.112.1
        immich:
          metrics:
            enabled: true
          persistence:
            library:
              existingClaim: immich-nfs
        machine-learning:
          persistence:
            cache:
              enabled: true
              size: 10Gi
              type: pvc
              accessMode: ReadWriteMany
              storageClass: longhorn
        postgresql:
          enabled: true
          global:
            auth:
              database: immich
              username: immich
              existingSecret: "immich-postgress-user-password"
              secretKeys:
                userPasswordKey: "password"
        redis:
          enabled: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

