apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: immich
    server: 'https://kubernetes.default.svc'
  source:
    path: 'charts/immich'
    repoURL: 'https://immich-app.github.io/immich-charts'
    targetRevision: v0.10.3 #DO NOT UPGRADE TO VERSION 0.10.0 until you migrate postgresql!
    # possible upgrade paths https://github.com/camrossi/home-cluster/blob/main/apps/immich/DB_Migration.md
    # https://gist.github.com/kabakaev/1d8fa31d4e7fa8134c968101fa88d200
    chart: immich
    helm:
      valueFiles: []
      values: |
        immich:
          metrics:
            enabled: true
          persistence:
            library:
              existingClaim: immich-nfs

        machine-learning:
          persistence:
            cache:
              enabled: true
              size: 10Gi
              type: persistentVolumeClaim
              accessMode: ReadWriteMany
              storageClass: longhorn

        valkey:
          enabled: true

        controllers:
          main:
            containers:
              main:
                image:
                  tag: v1.140.1
                env:
                  DB_HOSTNAME: "immich-postgres-cluster-rw.cnpg-database"
                  DB_USERNAME: "immich"
                  DB_DATABASE_NAME: "immich"
                  DB_PASSWORD:
                    valueFrom:
                      secretKeyRef:
                        name: "immich-postgress-user-password"
                        key: "password"


  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

