apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: v1.5.0
    chart: longhorn
    helm:
      valueFiles: []
      parameters:
        - name: ingress.enabled
          value: "true"
        - name: ingress.ingressClassName
          value: "private-nginx"
        - name: ingress.host
          value: "longhorn.andrewsutliff.com"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
