apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-supporting
  namespace: argocd
spec:
  destination:
    name: ''
    #namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  source:
    path: "Manifests/Storage"
    repoURL: >-
      https://github.com/Tanchwa/Homelab-IaC
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

