apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: v1.6.2
    chart: longhorn
    helm:
      valueFiles: []
      values: |
        ingress:
          host: longhorn.andrewsutliff.com
          enabled: true
          ingressClassName: private-nginx
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultDataLocality: best-effort
          replicaAutoBalance: least-effort
          backupTarget: "nfs://172.31.0.15//mnt/Main/kubernetes/backup"
          orphanAutoDeletion: "true"
          autoDeletePodWhenVolumeDetachedUnexpectedly: true
          nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
          nodeDrainPolicy: allways-allow
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
