- name: Create Celium CLI shell script install
  copy: 
    content: |
      #!/bin/bash
      export CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
      export CLI_ARCH=amd64
      curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
      sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
      sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
      rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    dest: /home/{{ kube_user }}/cilium_install.sh 
    mode: 0755

- name: Run CLI Shell Script
  become: true
  become_user: "{{ kube_user }}"
  shell: /home/{{ kube_user }}/cilium_install.sh
  args:
    executable: /bin/bash
  register: script_output

- name: Display Script Output
  debug:
    var: script_output.stdout_lines

- name: Remove Temporary Script
  file:
    path: /home/{{ kube_user }}/celium-install.sh
    state: absent

# - name: Unzip the tarball
#   become: true
#   become_user: "{{ kube_user }}"
#   unarchive:
#     src: cilium-linux-amd64.tar.gz
#     dest: /usr/local/bin
#     creates: /usr/local/bin/cilium
#     remote_src: true

# - name: remove tar files
#   file:
#     path: /home/{{ kube_user }}/{{ item }}
#     state: absent
#   with_items:
#     - cilium-linux-amd64.tar.gz
#     - cilium-linux-amd64.tar.gz.sha256sum

- name: Install Celium
  shell: |
    cilium install --version 1.14.2 \
    --namespace kube-system \
    --set l2announcements.enabled=true \
    --set l2announcements.leaseDuration=25s
    --set l2announcements.leaseRenewalDeadline=15s \
    --set l2announcements.leaseRetryPeriod=8s \
    --set k8sClientRateLimit.qps=3000 \
    --set k8sClientRateLimit.burst=20000 \
    --set kubeProxyReplacement=true \
    --set devices=enp+ \
    --set externalIPs.enabled=true 


# much more debugging needs to be done, for starters to use L2 aware LB, you need to use these options when installing 
# https://docs.cilium.io/en/stable/network/l2-announcements/#prerequisites

# $ helm upgrade cilium cilium/cilium --version 1.14.2 \
# --namespace kube-system \
# --set l2announcements.enabled=true \
# --set l2announcements.leaseDuration=25s
# --set l2announcements.leaseRenewalDeadline=15s \
# --set l2announcements.leaseRetryPeriod=8s \
# --set k8sClientRateLimit.qps=3000 \
# --set k8sClientRateLimit.burst=20000 \
# --set kubeProxyReplacement=true \
# --set devices=enp+ \
# --set externalIPs.enabled=true 

# --set k8sServiceHost=192.168.1.31 \
# --set k8sServicePort=6443 \
#default lease duration is 15s, renew deadline is 5s, increased both by 10
# level=info msg="  --l2-announcements-lease-duration='15s'" subsys=daemon
# level=info msg="  --l2-announcements-renew-deadline='5s'" subsys=daemon
# level=info msg="  --l2-announcements-retry-period='2s'" subsys=daemon

# TODO - Make a check if cilium is already running, if so use cilium config set key value, values are differently named
# enable-l2-announcements                           true
# k8s-client-qps                                    3000
# k8s-client-burst                                  20000
# kube-proxy-replacement                            strict
# devices                                           enp+